import type { Medicine } from "../../types/domain";

import product1 from "../../assets/products/product-1.svg";
import product2 from "../../assets/products/product-2.svg";
import product3 from "../../assets/products/product-3.svg";

export const demoMedicines: Medicine[] = [
  {
    id: "m-para-500",
    name: "Paracetamol 500mg",
    brand: "Medigo",
    category: "Medicines",
    description: "Common pain reliever and fever reducer.",
    price: 20,
    stockQty: 64,
    isPublished: true,
    imageUrl: product1,
  },
  {
    id: "m-ibuprofen-200",
    name: "Ibuprofen 200mg",
    brand: "HealWell",
    category: "Medicines",
    description: "Helps reduce inflammation and relieve pain.",
    price: 35,
    stockQty: 18,
    isPublished: true,
    imageUrl: product2,
  },
  {
    id: "m-vitc-1000",
    name: "Vitamin C 1000mg",
    brand: "VitaPlus",
    category: "Vitamins & Supplements",
    description: "Daily immune support supplement.",
    price: 220,
    stockQty: 0,
    isPublished: true,
    imageUrl: product2,
  },
  {
    id: "m-cetirizine-10",
    name: "Cetirizine 10mg",
    brand: "AllerFree",
    category: "Medicines",
    description: "Non-drowsy antihistamine for allergy relief.",
    price: 55,
    stockQty: 25,
    isPublished: true,
    imageUrl: product3,
  },
  {
    id: "m-omz-20",
    name: "Omeprazole 20mg",
    brand: "GastroCare",
    category: "Medicines",
    description: "Helps reduce stomach acid and heartburn.",
    price: 80,
    stockQty: 12,
    isPublished: true,
    imageUrl: product1,
  },
  {
    id: "m-zinc-20",
    name: "Zinc 20mg",
    brand: "VitaPlus",
    category: "Vitamins & Supplements",
    description: "Daily zinc supplement for immunity support.",
    price: 180,
    stockQty: 30,
    isPublished: true,
    imageUrl: product2,
  },
  {
    id: "m-skin-wash",
    name: "Gentle Face Wash",
    brand: "SkinLoving",
    category: "Personal Care",
    description: "Mild cleanser for sensitive skin.",
    price: 350,
    stockQty: 9,
    isPublished: true,
    imageUrl: product3,
  },
  {
    id: "m-glucometer",
    name: "Glucometer Kit",
    brand: "AccuCheck",
    category: "Diabetic Care",
    description: "Monitor blood glucose at home.",
    price: 1250,
    stockQty: 6,
    isPublished: true,
    imageUrl: product1,
  },
];
